name             'chef-perdition'
maintainer       'Stephane LII'
maintainer_email 'stephane.lii@informatique.gov.pf'
license          'All rights reserved'
description      'Installs/Configures chef-perdition'
long_description 'Installs/Configures chef-perdition'
version          '0.1.0'
depends 'apt'
